name: Docker

on:
  push:
    branches: 
      - master
  schedule:
    - cron: "0 0 * * *"

env:
  IMAGE_NAME: b2

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: jmmaloney4
          password: ${{ secrets.DOCKER_HUB_PAT }}
          repository: jmmaloney4/b2
          tags: latest, ${{github.run_number}}
