name: Docker

on:
  push:
    branches: 
      - master
  schedule:
    - cron: "0 0 * * *"

env:
  IMAGE_NAME: b2

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: jmmaloney4
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          repository: jmmaloney4/b2
          tags: |
            jmmaloney4/b2:latest
            jmmaloney4/b2:${{github.run_number}}
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
